In [ ]:
import pandas as pd

In [2]:
df=pd.read_csv("Student_Performance.csv")

In [3]:
df.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Hours Studied                     10000 non-null  int64  
 1   Previous Scores                   10000 non-null  int64  
 2   Extracurricular Activities        10000 non-null  object 
 3   Sleep Hours                       10000 non-null  int64  
 4   Sample Question Papers Practiced  10000 non-null  int64  
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB


In [5]:
df.isna().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [6]:
df["Extracurricular Activities"]

0       Yes
1        No
2       Yes
3       Yes
4        No
       ... 
9995    Yes
9996    Yes
9997    Yes
9998    Yes
9999     No
Name: Extracurricular Activities, Length: 10000, dtype: object

In [7]:
df["Extracurricular Activities"].unique()

array(['Yes', 'No'], dtype=object)

In [8]:
def encoding(df):
    if df["Extracurricular Activities"]=="Yes":
        return 1
    else:
         return 0

In [9]:
df["Extracurricular Activities"]=df.apply(encoding,axis=1)

In [10]:
df

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0                 7               99                           1            9   
1                 4               82                           0            4   
2                 8               51                           1            7   
3                 5               52                           1            5   
4                 7               75                           0            8   
...             ...              ...                         ...          ...   
9995              1               49                           1            4   
9996              7               64                           1            8   
9997              6               83                           1            8   
9998              9               97                           1            7   
9999              7               74                           0            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [11]:
input=df.drop("Performance Index",axis=1)
output=df["Performance Index"]

In [12]:
input

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0                 7               99                           1            9   
1                 4               82                           0            4   
2                 8               51                           1            7   
3                 5               52                           1            5   
4                 7               75                           0            8   
...             ...              ...                         ...          ...   
9995              1               49                           1            4   
9996              7               64                           1            8   
9997              6               83                           1            8   
9998              9               97                           1            7   
9999              7               74                           0            8   

      Sample Question Papers Practiced  
0                                    1  
1                                    2  
2                                    2  
3                                    2  
4                                    5  
...                                ...  
9995                                 2  
9996                                 5  
9997                                 5  
9998                                 0  
9999                                 1  

[10000 rows x 5 columns]

In [13]:
output

0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ... 
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: Performance Index, Length: 10000, dtype: float64

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train ,x_test,y_train,y_test=train_test_split(input,output,test_size=0.25,random_state=42)

In [16]:
x_train.shape

(7500, 5)

In [17]:
y_train.shape

(7500,)

In [18]:
x_test.shape,y_test.shape

((2500, 5), (2500,))

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_train=scaler.fit_transform(x_train)
scaled_train

array([[ 0.00796272, -1.19062085, -0.98912579, -0.90874945,  0.13314392],
       [ 0.77854894,  1.05902612,  1.01099376, -1.49731775,  1.53122497],
       [-0.76262349,  1.40512565,  1.01099376,  0.26838714, -1.26493713],
       ...,
       [ 1.54913515, -1.24830411, -0.98912579,  0.26838714,  0.48266418],
       [-1.5332097 , -1.30598737, -0.98912579,  1.44552374, -1.6144574 ],
       [-1.14791659, -1.36367062, -0.98912579, -0.32018115,  0.48266418]],
      shape=(7500, 5))

In [20]:
scaled_test = scaler.transform(x_test)
scaled_test

array([[ 0.00796272, -0.03695574, -0.98912579,  0.85695544, -0.91541687],
       [-1.14791659, -1.36367062,  1.01099376, -1.49731775,  1.18170471],
       [ 0.77854894, -0.78683806,  1.01099376,  0.26838714,  0.13314392],
       ...,
       [ 0.00796272,  0.65524333, -0.98912579,  0.85695544,  1.18170471],
       [-0.37733038,  0.13609403, -0.98912579, -0.90874945, -0.56589661],
       [ 1.16384204, -0.44073853,  1.01099376, -1.49731775, -0.91541687]],
      shape=(2500, 5))

In [21]:
x_train[x_train.columns]=scaled_train

In [22]:
x_train.head()

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
4901       0.007963        -1.190621                   -0.989126    -0.908749   
4375       0.778549         1.059026                    1.010994    -1.497318   
6698      -0.762623         1.405126                    1.010994     0.268387   
9805       1.549135        -0.902205                    1.010994    -0.908749   
1101      -0.377330        -0.786838                    1.010994     0.856955   

      Sample Question Papers Practiced  
4901                          0.133144  
4375                          1.531225  
6698                         -1.264937  
9805                          1.531225  
1101                          0.482664

In [23]:
x_test[x_test.columns]=scaled_test

In [24]:
x_test.head()

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
6252       0.007963        -0.036956                   -0.989126     0.856955   
4684      -1.147917        -1.363671                    1.010994    -1.497318   
1731       0.778549        -0.786838                    1.010994     0.268387   
4742       0.393256        -1.594404                    1.010994     0.856955   
4521       0.778549        -0.959888                   -0.989126    -1.497318   

      Sample Question Papers Practiced  
6252                         -0.915417  
4684                          1.181705  
1731                          0.133144  
4742                          0.133144  
4521                          0.482664

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
model=LinearRegression()

In [27]:
model.fit(x_train,y_train)

LinearRegression()

In [28]:
y_hat_train=model.predict(x_train)

In [29]:
y_hat_train

array([33.54641554, 79.76556481, 74.34741774, ..., 45.09441177,
       21.04688907, 22.60032134], shape=(7500,))

In [30]:
model.coef_

array([ 7.40973867, 17.62000334,  0.29183721,  0.81024328,  0.54624431])

In [31]:
model.intercept_

np.float64(55.41839999999999)

In [32]:
y_hat_test=model.predict(x_test)

In [33]:
y_hat_test

array([54.73187888, 22.61211054, 47.90838844, ..., 68.07396952,
       53.68636805, 54.85816372], shape=(2500,))

In [34]:
from sklearn.metrics import mean_squared_error, root_mean_squared_error

In [35]:
test_mse = mean_squared_error(y_test, y_hat_test)
test_mse

4.032544215419119

In [36]:
rmse_train = root_mean_squared_error(y_train, y_hat_train)
rmse_train

2.0478584279022196

In [37]:
rmse_test = root_mean_squared_error(y_test, y_hat_test)
rmse_test

2.0081195719924447

In [38]:
import joblib
joblib.dump(model,"Student_performance.pkl")

['Student_performance.pkl']

In [39]:
joblib.dump(scaler, "scaler.pkl")


['scaler.pkl']